# Generated by Django 2.2.3 on 2019-07-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0002_remove_stuff_markdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='markdown',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
