# Generated by Django 2.2.3 on 2019-07-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0003_stuff_markdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='category',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stuff',
            name='markdown',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True),
        ),
    ]
