# Generated by Django 2.2.3 on 2019-07-22 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('commutative', models.BooleanField()),
                ('markdown', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('slug', models.SlugField()),
                ('category', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
